//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L2, L5, L5, R5, L2, L4, R1, R1, L4, R2, R1, L1, L4, R1, L4, L4, R5, R3, R1, L1, R1, L5, L1, R5, L4, R2, L5, L3, L3, R3, L3, R4, R4, L2, L5, R1, R2, L2, L1, R3, R4, L193, R3, L5, R45, L1, R4, R79, L5, L5, R5, R1, L4, R3, R3, L4, R185, L5, L3, L1, R5, L2, R1, R3, R2, L3, L4, L2, R2, L3, L2, L2, L3, L5, R3, R4, L5, R1, R2, L2, R4, R3, L4, L3, L1, R3, R2, R1, R1, L3, R4, L5, R2, R1, R3, L3, L2, L2, R2, R1, R2, R3, L3, L3, R4, L4, R4, R4, R4, L3, L1, L2, R5, R2, R2, R2, L4, L3, L4, R4, L5, L4, R2, L4, L4, R4, R1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bot 153 gives low to bot 105 and high to bot 10
        ///bot 84 gives low to bot 149 and high to bot 198
        ///bot 32 gives low to bot 124 and high to bot 76
        ///bot 177 gives low to output 8 and high to bot 19
        ///bot 64 gives low to bot 6 and high to bot 179
        ///bot 115 gives low to bot 181 and high to bot 190
        ///bot 169 gives low to bot 21 and high to bot 60
        ///bot 106 gives low to bot 17 and high to bot 84
        ///bot 129 gives low to bot 52 and high to bot 57
        ///bot 208 gives low to bot 78 and high to bot 121
        ///bot 179 gives low to bot 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day10 {
            get {
                return ResourceManager.GetString("Day10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cpy 1 a
        ///cpy 1 b
        ///cpy 26 d
        ///jnz c 2
        ///jnz 1 5
        ///cpy 7 c
        ///inc d
        ///dec c
        ///jnz c -2
        ///cpy a c
        ///inc a
        ///dec b
        ///jnz b -2
        ///cpy c b
        ///dec d
        ///jnz d -6
        ///cpy 13 c
        ///cpy 14 d
        ///inc a
        ///dec d
        ///jnz d -2
        ///dec c
        ///jnz c -5
        ///.
        /// </summary>
        internal static string Day12 {
            get {
                return ResourceManager.GetString("Day12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URULLLLLRLDDUURRRULLLDURRDRDRDLURURURLDLLLLRUDDRRLUDDDDDDLRLRDDDUUDUDLDULUDLDURDULLRDDURLLLRRRLLRURLLUDRDLLRRLDDRUDULRRDDLUUUDRLDLURRRULURRDLLLDDDLUDURDDRLDDDLLRULDRUDDDLUDLURUDLLRURRUURUDLLLUUUUDDURDRDDDLDRRUDURDLLLULUDURURDUUULRULUDRUUUUDLRLUUUUUDDRRDDDURULLLRRLDURLDLDRDLLLUULLRRLLLLDRLRDRRDRRUDDLULUUDDDDRRUUDDLURLRDUUDRRLDUDLRRRLRRUUDURDRULULRDURDRRRDLDUUULRDDLRLRDLUUDDUDDRLRRULLLULULLDDDRRDUUUDDRURDDURDRLRDLDRDRULRLUURUDRLULRLURLRRULDRLRDUDLDURLLRLUDLUDDURDUURLUDRLUL
        ///LLLUUURUULDDDULRRDLRLLLLLLLLRURRDLU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   330  143  338
        ///  769  547   83
        ///  930  625  317
        ///  669  866  147
        ///   15  881  210
        ///  662   15   70
        ///  273  277  707
        ///   50  592  770
        ///  280  313  407
        ///  642  487  372
        ///   94  619  295
        ///  734  243  141
        ///  220  141  515
        ///  198  824  745
        ///  210  787  964
        ///  213  627  601
        ///  918    4  447
        ///  805  630  802
        ///  711  237  987
        ///  938  552  388
        ///  643  405  779
        ///  803  747  525
        ///  917  832  631
        ///  899  292  843
        ///   81  206  445
        ///  141  874  465
        ///  177  974   54
        ///  520  725  814
        ///  271  958  554
        ///  779  579  264
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fubrjhqlf-edvnhw-dftxlvlwlrq-803[wjvzd]
        ///kzgwomvqk-rmttgjmiv-lmxizbumvb-902[zmnji]
        ///dkqjcbctfqwu-dwppa-fgukip-596[syiua]
        ///xjinphzm-bmvyz-ytz-gjbdnodxn-135[nzbdj]
        ///uwtojhynqj-hfsid-xytwflj-177[ztsqu]
        ///udpsdjlqj-fkrfrodwh-ilqdqflqj-491[uscwt]
        ///kdijqrbu-fbqijys-whqii-sedjqydcudj-790[dijqb]
        ///udpsdjlqj-hjj-uhdftxlvlwlrq-439[jldhq]
        ///bnmrtldq-fqzcd-bqxnfdmhb-bgnbnkzsd-zmzkxrhr-105[bdnzm]
        ///lejkrscv-wlqqp-sleep-ivrthlzjzkzfe-789[elzjk]
        ///zlilocri-ciltbo-obxznrfpfqflk-419[spmzt]
        ///tyepcyletzylw-nsznzwlep-qtylyntyr-821[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tmcezlum
        ///afzwmyrz
        ///ollxkaqs
        ///oqvdutkr
        ///ufzmsidi
        ///wnidhqow
        ///efgwivmh
        ///endrsvkk
        ///nraaoczx
        ///yghmfumn
        ///fcwrdzyt
        ///qbbejygt
        ///ohrzbtul
        ///lmrarckg
        ///frzhozsk
        ///ahvqozmk
        ///cnoxuqjm
        ///njudcxbx
        ///xjeohiim
        ///sygfjxcx
        ///fbmchcaa
        ///qqggrcwq
        ///vbcgurox
        ///eujzkdmh
        ///kbpinltk
        ///posxqzam
        ///rojnpogl
        ///zvhruwqw
        ///hvbrxcky
        ///iqifiukd
        ///xetwaptt
        ///qvksnzoe
        ///nulslfja
        ///tphqwfte
        ///ddencvfp
        ///nhabbwcl
        ///jefzkclw
        ///txstxeio
        ///yaaqxpdp
        ///efewzeqa
        ///teapznjk
        ///jylnjhnf
        ///jumelmrz
        ///ziarkfwo
        ///vklsvaca
        ///uoyzpkbn
        ///oovggzkn
        ///ajvmcuon
        ///gkztjkss
        ///qnwohfwg
        ///kxwtvaez
        ///jw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day6 {
            get {
                return ResourceManager.GetString("Day6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wysextplwqpvipxdv[srzvtwbfzqtspxnethm]syqbzgtboxxzpwr[kljvjjkjyojzrstfgrw]obdhcczonzvbfby[svotajtpttohxsh]cooktbyumlpxostt
        ///emzopymywhhxulxuctj[dwwvkzhoigmbmnf]nxgbgfwqvrypqxppyq[qozsihnhpztcrpbdc]rnhnakmrdcowatw[rhvchmzmyfxlolwe]uysecbspabtauvmixa
        ///bqooxxweoytjghrqn[hkwwukixothfyglw]kpasnmikmbzcbfi[vlnyszifsaaicagxtqf]ucdyxasusefuuxlx
        ///rxpusykufgqujfe[rypwoorxdemxffui]cvvcufcqmxoxcphp[witynplrfvquduiot]vcysdcsowcxhphp[gctucefriclxaonpwe]jdprpdvpeumrhokrcjt
        ///iungssgfnnjlgdferc[xfffplonmzjmxkinhl]dehxdielvnc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day7 {
            get {
                return ResourceManager.GetString("Day7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rect 1x1
        ///rotate row y=0 by 5
        ///rect 1x1
        ///rotate row y=0 by 5
        ///rect 1x1
        ///rotate row y=0 by 3
        ///rect 1x1
        ///rotate row y=0 by 2
        ///rect 1x1
        ///rotate row y=0 by 3
        ///rect 1x1
        ///rotate row y=0 by 2
        ///rect 1x1
        ///rotate row y=0 by 5
        ///rect 1x1
        ///rotate row y=0 by 5
        ///rect 1x1
        ///rotate row y=0 by 3
        ///rect 1x1
        ///rotate row y=0 by 2
        ///rect 1x1
        ///rotate row y=0 by 3
        ///rect 2x1
        ///rotate row y=0 by 2
        ///rect 1x2
        ///rotate row y=1 by 5
        ///rotate row y=0 by 3
        ///rect 1x2
        ///rotate column x=30 by 1
        ///rotate column x=25 by 1
        ///rotate column x=10 by 1
        ///rot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day8 {
            get {
                return ResourceManager.GetString("Day8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (192x7)(1x15)D(39x15)(4x7)OUHB(13x12)AVYCACVMBVXVK(5x2)SUKJR(7x6)YUITKFT(12x4)(6x13)FDBLGI(102x8)(14x3)DSOUOPGYXFJRFJ(30x3)MUFOGDZOXXFEVPIXISTPRPMNKCSNPC(1x8)R(33x13)AIHJBMADPXTMXMZLDYQMEJSXOLHUTCEWV(6x14)OWSJRJ(12x4)BSITDMDRQBHM(132x6)(28x6)YOIWLWAAUBGAKOAERRZSJCADASVS(14x10)KAPJYKZCAIAOZV(54x3)(1x9)V(18x13)TEBMXRFAJUDQGFVUZZ(16x13)LELBCBPXEFTWYFKM(11x4)(5x12)VNSTD(262x8)(23x3)VFTGNXFKADBQZUKOLBBEGTB(30x10)(2x7)SV(1x4)A(10x12)EUDDBQIUFK(22x4)RGLTWOGGQXYBBQXTHHTBQY(108x7)(5x7)GXEWH(26x1)PADMQZDXHPVOMNKUEYAV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day9 {
            get {
                return ResourceManager.GetString("Day9", resourceCulture);
            }
        }
    }
}
