[alias] # command aliases
all = "run"
day = "run --bin day"
ci = ["watch", "--clear", "-x", "test --doc", "-x", "run", "-x", "bench"]
wb = "watch --clear -x bench"
everything-forever = "watch --clear -x test -x run -x bench"
